/**
 * How each catalog symbol is named in headlines. All-caps aliases (tickers) match case-sensitively so
 * "SOL" or "TON" do not fire on ordinary words; everything else matches case-insensitively. Ambiguous
 * tickers (OP, ARB…) are left out on purpose — the name is enough.
 */
export const NEWS_ALIASES: Record<string, string[]> = {
  // Crypto
  "BTC/USDT": ["Bitcoin", "BTC"],
  "ETH/USDT": ["Ethereum", "Ether", "ETH"],
  "BNB/USDT": ["BNB", "BNB Chain"],
  "SOL/USDT": ["Solana", "SOL"],
  "XRP/USDT": ["XRP", "Ripple"],
  "ADA/USDT": ["Cardano", "ADA"],
  "AVAX/USDT": ["Avalanche", "AVAX"],
  "DOGE/USDT": ["Dogecoin", "DOGE"],
  "TRX/USDT": ["TRON", "TRX"],
  "DOT/USDT": ["Polkadot", "DOT"],
  "LINK/USDT": ["Chainlink", "LINK"],
  "UNI/USDT": ["Uniswap", "UNI"],
  "LTC/USDT": ["Litecoin", "LTC"],
  "ATOM/USDT": ["Cosmos Hub", "ATOM"],
  "NEAR/USDT": ["NEAR Protocol"],
  "APT/USDT": ["Aptos", "APT"],
  "OP/USDT": ["Optimism network", "OP Mainnet"],
  "ARB/USDT": ["Arbitrum"],
  "SUI/USDT": ["Sui network", "SUI"],
  "TON/USDT": ["Toncoin", "TON"],
  "FIL/USDT": ["Filecoin"],
  "PEPE/USDT": ["Pepe", "PEPE"],
  "SHIB/USDT": ["Shiba Inu", "SHIB"],
  "FLOKI/USDT": ["Floki"],
  "WIF/USDT": ["dogwifhat", "WIF"],
  "BONK/USDT": ["Bonk"],
  "FARTCOIN/USD": ["Fartcoin"],
  // Indices
  SPX: ["S&P 500", "S&P500", "SPX"],
  NDX: ["Nasdaq"],
  DJI: ["Dow Jones", "Dow Industrials", "DJIA"],
  FTSE: ["FTSE 100", "FTSE"],
  DAX: ["DAX"],
  N225: ["Nikkei"],
  HSI: ["Hang Seng"],
  TSX: ["TSX"],
  SHCOMP: ["Shanghai Composite"],
  ESTX50: ["Euro Stoxx", "STOXX 50"],
  CAC40: ["CAC 40", "CAC"],
  BVSP: ["Bovespa", "Ibovespa"],
  ASX200: ["ASX 200", "ASX"],
  IPC: ["Mexican stocks", "Mexico's IPC"],
  BVLPG: ["Lima stock exchange"],
  JSE40: ["JSE"],
  KOSPI: ["KOSPI", "Kospi"],
  RUT: ["Russell 2000"],
  IBEX: ["IBEX 35", "IBEX"],
  // Commodities
  "XAU/USD": ["gold", "XAU"],
  "XAG/USD": ["silver", "XAG"],
  WTI: ["WTI", "crude oil", "oil prices"],
  BRENT: ["Brent"],
  NG: ["natural gas"],
  COPPER: ["copper"],
  // Forex
  "EUR/USD": ["EUR/USD", "EURUSD", "euro"],
  "GBP/USD": ["GBP/USD", "GBPUSD", "sterling", "British pound"],
  "USD/JPY": ["USD/JPY", "USDJPY", "yen"],
  "USD/CHF": ["USD/CHF", "USDCHF", "Swiss franc"],
  "AUD/USD": ["AUD/USD", "AUDUSD", "Australian dollar", "Aussie dollar"],
  "USD/CAD": ["USD/CAD", "USDCAD", "Canadian dollar", "loonie"],
  "NZD/USD": ["NZD/USD", "NZDUSD", "New Zealand dollar", "kiwi dollar"],
  "EUR/GBP": ["EUR/GBP", "EURGBP"],
  "EUR/JPY": ["EUR/JPY", "EURJPY"],
  "USD/TRY": ["USD/TRY", "USDTRY", "Turkish lira", "lira"],
};
