/** The risk disclaimer and terms of use — one source for /welcome and /legal. Draft: have it reviewed by a lawyer before public launch. */
export function RiskPoints() {
  return (
    <ul className="list-disc space-y-2 pl-5">
      <li><strong className="text-ink">Not financial advice.</strong> AlphaBoard is an analysis and education tool. Nothing in it is a recommendation to buy or sell any asset, and it does not know your finances, goals or risk tolerance.</li>
      <li><strong className="text-ink">AI output can be wrong.</strong> Strategy reports, confidence scores, post-mortems and chart studies are generated by third-party AI models. They can be inaccurate, outdated or confidently mistaken. Past signal performance does not predict future results.</li>
      <li><strong className="text-ink">Market data may be delayed or missing.</strong> Prices come from public sources (Binance, Yahoo Finance and others) without guarantees. When data is unavailable, AlphaBoard says so rather than guessing, but outages and errors are possible.</li>
      <li><strong className="text-ink">Paper trading is simulated.</strong> Paper fills use a simple model (0.05% slippage and fee). Real markets have gaps, liquidity limits, funding and other costs that simulated results do not capture. AlphaBoard never places real orders.</li>
      <li><strong className="text-ink">Trading carries risk.</strong> Leveraged and crypto trading can lose more than you expect, quickly. Only trade with money you can afford to lose, and consider independent, licensed advice.</li>
      <li><strong className="text-ink">Your responsibility.</strong> You alone are responsible for your trading decisions and their outcomes.</li>
    </ul>
  );
}

export function TermsPoints() {
  return (
    <ul className="list-disc space-y-2 pl-5">
      <li>Access is by invitation only. Keep your login to yourself; accounts are personal.</li>
      <li>Don&apos;t misuse the service: no automated scraping, no attempts to bypass limits, no use against the law of your country.</li>
      <li>Your journal, signals, screenshots and settings are stored in AlphaBoard&apos;s database and are visible only to you (and to administrators when needed to operate the service). AI features send the relevant data to the selected AI provider.</li>
      <li>The service is provided as is, without warranties, and may change or stop. To the extent the law allows, AlphaBoard and its operators are not liable for trading losses or decisions based on it.</li>
    </ul>
  );
}
